### PR TITLE
Added initial Definition of Done.

### PR DESCRIPTION
**Pull request by sunnehh**
Wrote a very basic definition of done.
If ya'll have anything to add, please do.

### CODE REVIEW

**Review by MichaelKlmn — COMMENTED** [review]
Looks good to me! 

I might add a bit more in the documentation section regarding whitespaces and leaving space in between lines of code for cleaner, more efficient viewing.

**Review by MichaelKlmn — APPROVED** [review]
Looks good to me!

I might add a bit more in the documentation section regarding whitespaces and leaving space in between lines of code for cleaner, more efficient viewing.

**Comment by sunnehh** [comment]
I'll merge it for now and formatting can be taken care of by another member later? lmk how that sounds @MichaelKl04

**Review by AmirHoseinFj — APPROVED** [review]
Looks great

**Pull request merged**
