### PR TITLE
Workout planner app proposal

### PR DESCRIPTION
**Pull request by sunnehh**
Integrated joshua's ideas into my branch.

## changes:
- did away with the complex technologies previously proposed in favor of more easily implementable solution

## notes:
- kept formatting of original outline. please make note of whether we want to do away with this or not?

### CODE REVIEW

**Review by joshuadinham — APPROVED** [review]
Changes look good

**Comment by joshuadinham** [comment]
Ready for merge

**Review by MichaelKlmn — COMMENTED** [review]
lgtm

**Review by AmirHoseinFj — COMMENTED** [review]
Looks good

**Pull request merged**
